// See https://aka.ms/new-console-template for more information

using System.Diagnostics;
using System.Linq;
using DotNetGameFramework.JsonDB;

String json = "{\"techs\":[1,2,3,4,5]}";
            json = @"{
    ""teamId"": 175934012007827456,
    ""teamName"": ""金1"",
    ""teamIcon"": ""nanzhujue"",
    ""teamLv"": 39,
    ""combatPower"": 1584750,
    ""generals"": [
        {
            ""id"": 2296,
            ""generalId"": 101052,
            ""loc"": 3,
            ""lv"": 112,
            ""rankLv"": 4,
            ""star"": 7,
            ""combatPower"": 259315,
            ""skillId"": 101052,
            ""triggerSkillIds"": [
                10105201,
                10105202,
                10105203
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                1
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": [],
            ""equipList"": [
                {
                    ""equipId"": 50102,
                    ""lv"": 0,
                    ""loc"": 0,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50101,
                    ""lv"": 0,
                    ""loc"": 1,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50103,
                    ""lv"": 0,
                    ""loc"": 2,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [
                        {
                            ""left"": 6,
                            ""right"": ""cri_resist_p=5""
                        }
                    ],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50104,
                    ""lv"": 0,
                    ""loc"": 3,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                }
            ],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 385163,
                ""att"": 70698,
                ""def"": 10150,
                ""mdef"": 8808,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 150346,
                ""att"": 21828,
                ""def"": 7065,
                ""mdef"": 7065,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""shengdianAttr"": {
                ""hp"": 24252,
                ""att"": 2615,
                ""def"": 133,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""buffAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""teamAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""priorityAttr"": {
                ""hp"": 128745,
                ""att"": 18076,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        },
        {
            ""id"": 4152,
            ""generalId"": 101037,
            ""loc"": 1,
            ""lv"": 100,
            ""rankLv"": 0,
            ""star"": 5,
            ""combatPower"": 107298,
            ""skillId"": 101037,
            ""triggerSkillIds"": [
                10103701,
                10103702,
                0
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                0
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": [],
            ""equipList"": [],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 166201,
                ""att"": 28630,
                ""def"": 17814,
                ""mdef"": 15148,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""shengdianAttr"": {
                ""hp"": 20271,
                ""att"": 1914,
                ""def"": 210,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""buffAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""teamAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""priorityAttr"": {
                ""hp"": 42888,
                ""att"": 5803,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        },
        {
            ""id"": 2762,
            ""generalId"": 101083,
            ""loc"": 5,
            ""lv"": 100,
            ""rankLv"": 3,
            ""star"": 5,
            ""combatPower"": 106298,
            ""skillId"": 101083,
            ""triggerSkillIds"": [
                10108301,
                10108302,
                0
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                0
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": [],
            ""equipList"": [],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 159034,
                ""att"": 33174,
                ""def"": 8915,
                ""mdef"": 7589,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""shengdianAttr"": {
                ""hp"": 20015,
                ""att"": 1947,
                ""def"": 121,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""buffAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""teamAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""priorityAttr"": {
                ""hp"": 41181,
                ""att"": 6672,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        },
        {
            ""id"": 2891,
            ""generalId"": 101079,
            ""loc"": 4,
            ""lv"": 100,
            ""rankLv"": 0,
            ""star"": 5,
            ""combatPower"": 102566,
            ""skillId"": 101079,
            ""triggerSkillIds"": [
                10107901,
                10107902,
                0
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                0
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": [],
            ""equipList"": [],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 181759,
                ""att"": 19454,
                ""def"": 32144,
                ""mdef"": 27318,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""shengdianAttr"": {
                ""hp"": 20279,
                ""att"": 1790,
                ""def"": 353,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""buffAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""teamAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""priorityAttr"": {
                ""hp"": 46468,
                ""att"": 4036,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        },
        {
            ""id"": 3027,
            ""generalId"": 101047,
            ""loc"": 2,
            ""lv"": 100,
            ""rankLv"": 0,
            ""star"": 5,
            ""combatPower"": 102484,
            ""skillId"": 101047,
            ""triggerSkillIds"": [
                10104701,
                10104702,
                0
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                0
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": [],
            ""equipList"": [],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 185586,
                ""att"": 19063,
                ""def"": 31948,
                ""mdef"": 27318,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""shengdianAttr"": {
                ""hp"": 20343,
                ""att"": 1783,
                ""def"": 351,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""buffAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""teamAttr"": {
                ""hp"": 0,
                ""att"": 0,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""priorityAttr"": {
                ""hp"": 47363,
                ""att"": 3960,
                ""def"": 0,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        },
        {
            ""id"": 5,
            ""generalId"": 101010,
            ""loc"": 0,
            ""lv"": 100,
            ""rankLv"": 3,
            ""star"": 8,
            ""combatPower"": 882489,
            ""skillId"": 101010,
            ""triggerSkillIds"": [
                10101001,
                10101002,
                0
            ],
            ""skillLvs"": [
                2,
                1,
                1,
                0
            ],
            ""skin"": 0,
            ""virtualSkillId"": 0,
            ""virtualSummonId"": 0,
            ""virtualSummonStar"": 0,
            ""contractSkillList"": null,
            ""equipList"": [
                {
                    ""equipId"": 50102,
                    ""lv"": 0,
                    ""loc"": 0,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50101,
                    ""lv"": 0,
                    ""loc"": 1,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50103,
                    ""lv"": 0,
                    ""loc"": 2,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                },
                {
                    ""equipId"": 50104,
                    ""lv"": 0,
                    ""loc"": 3,
                    ""suitId"": 0,
                    ""suitNum"": 0,
                    ""star"": 1,
                    ""skillList"": [],
                    ""combatPower"": 0
                }
            ],
            ""suitSkill"": {},
            ""baseAttr"": {
                ""hp"": 152532,
                ""att"": 23620,
                ""def"": 17766,
                ""mdef"": 15148,
                ""cri"": 100,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""equipAttr"": {
                ""hp"": 2896236,
                ""att"": 253570,
                ""def"": 24252,
                ""mdef"": 24252,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""summonAttr"": null,
            ""shengdianAttr"": null,
            ""buffAttr"": null,
            ""teamAttr"": null,
            ""priorityAttr"": null
        }
    ],
    ""summons"": [
        {
            ""id"": 101,
            ""loc"": 0,
            ""lv"": 25,
            ""star"": 3,
            ""skillLv"": 0,
            ""priority"": 0,
            ""skills"": [
                101011,
                101021,
                0
            ],
            ""skillLvs"": [
                1,
                1,
                1
            ],
            ""virtualSkillId"": 0,
            ""attr"": {
                ""hp"": 308466,
                ""att"": 49288,
                ""def"": 26934,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            },
            ""attrE"": {
                ""hpE"": 0,
                ""attE"": 0,
                ""defE"": 0,
                ""mdefE"": 0
            },
            ""totalAttr"": {
                ""hp"": 308466,
                ""att"": 49288,
                ""def"": 26934,
                ""mdef"": 0,
                ""cri"": 0,
                ""criResist"": 0,
                ""criDam"": 0,
                ""criDamResist"": 0,
                ""hit"": 0,
                ""dodge"": 0,
                ""thrust"": 0,
                ""block"": 0,
                ""blockRa"": 0,
                ""blockRaResisit"": 0,
                ""damDeep"": 0,
                ""damResist"": 0,
                ""cure"": 0,
                ""cureResist"": 0,
                ""cureAtt"": 0,
                ""effectHit"": 0,
                ""effectDodge"": 0,
                ""criDamResistP"": 0,
                ""blockP"": 0
            }
        }
    ]
}
";
            // var jnode = JSON.Parse("{\"companyID\":\"15\",\"TestNum\":{\"test\":16, \"sort\":true},\"employees\":[{\"firstName\":\"Bill\",\"lastName\":\"Gates\"},{\"firstName\":\"George\",\"lastName\":\"Bush\"}],\"manager\":[{\"salary\":\"6000\",\"age\":\"23\"},{\"salary\":\"8000\",\"age\":\"26\"}]}");
            // var jnode = Parse(json);
            // // tree.SetValue("TestNum", "{\"test\":89, \"sort\":true, \"inc\":\"你好\"}");
            // jnode.AddJson("array", "[1,2,3,4]");
            // jnode.Append("array", 5);
            // jnode.Remove("employees.$1");

           
            var table = JSONTable.Create("songs");
            table.AddIndex("sex", false, "sex");
            table.AddIndex("age", false, "age");
            table.Insert("{\"title\":\"low1\",\"name\":\"will\",\"employees\":[{\"firstName\":\"Bill\",\"lastName\":\"Gates\"},{\"firstName\":\"George\",\"lastName\":\"Bush\"}]}");
            table.Insert("{\"title\":\"low1\",\"name\":\"will1\",\"age\":\"1\"}");
            
            // var max = 10000;
            // var random = new Random();
            // for (var i = 0; i < max; i++)
            // {
            //     table.Insert($@"{{""title"":""low{i}"",""name"":""will{i}"",""age"":{random.Next(max)}, ""sex"":""{(random.NextDouble() < 0.5 ? 1 : 2)}""}}");
            // }
            // max = 1000000;
            var time = Stopwatch.StartNew();
            // // var builder = new StringBuilder();
            // time.Start();
            // for (var i = 0; i < max; i++)
            // {
            //     var node = JSON.CreateRootNode();
            //     node.Add("title", $"low{i}");
            //     node.Add("name", $"will{i}");
            //     node.Add("age", random.Next(max));
            //     node.Add("sex", $"{(random.NextDouble() < 0.5 ? 1 : 2)}");
            //     // var str =
            //     //     $@"{{""title"":""low{i}"",""name"":""will{i}"",""age"":{random.Next(max)}, ""sex"":""{(random.NextDouble() < 0.5 ? 1 : 2)}""}}";
            //     table.Insert(node);
            //     // builder.Append(str);
            // }
            // time.Stop();
            // Console.WriteLine($"time:{time.ElapsedMilliseconds}");
            //
            // time.Restart();
            // table.Serialize("song.json");
            // time.Stop();
            
            // time.Restart();
            // table.Load("song.json");
            // time.Stop();
            // var fs = new FileStream("song.json", FileMode.Create);
            // fs.Write(Encoding.UTF8.GetBytes(a));
            // fs.Close();
            Console.WriteLine($"time:{time.ElapsedMilliseconds}, Count:{table.Table().Count}");
            time.Restart();
            List<JsonNode> a = null;
            for (var i = 0; i < 1000; i++)
            {
                a = (List<JsonNode>)table.Where(JSON.Eq("age", "1")).ToList();
            }
            time.Stop();
            Console.WriteLine($"time:{time.ElapsedMilliseconds}, count:{a[0]}");
            // var id = a.Get<string>("_id");
            // table.Delete(a.Get<string>("_id"));
            // Console.WriteLine($"id:{id}");
            // table.Update(id, Parse("{\"title\":\"low2\",\"name\":\"will1\",\"age\":\"1\"}"));
            // table.Get(id).Set("age", "22222");


            // dynamic d = new DynamicJsonNode(a);
            // d.age = "2";
            // Console.WriteLine($"{d.age}");
            // a?.AddJson("employees", "{\"firstName\":\"Bill1\",\"lastName\":\"Gates1\"}");
            // // tree.TryGetValue<JsonNode>("generals.$1", out var value);
            // // value.TryGetValue<int>("triggerSkillIds.$1", out var id);
            // Console.WriteLine($"value:{a}");

            // var n = jnode.Get<JsonNode>("generals");
            // dynamic obj = new DynamicJsonNode(jnode);
            // dynamic general = obj.generals[0];
            // dynamic priorityAttr = general.priorityAttr;
            // Console.WriteLine($"{priorityAttr.hp}");
            //
            //
            // var time = Stopwatch.StartNew();
            // time.Start();
            // long num = 1;
            // for (var i = 1; i < 10000000; i++)
            // {
            //     if (jnode.TryGetValue<int>("generals.$1.priorityAttr.hp", out var v))
            //     {
            //         num += v;
            //     }
            // }
            // time.Stop();
            // Console.WriteLine($"time:{time.ElapsedMilliseconds}, {num}");
            // Console.WriteLine($"{jnode}");